### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by derselbst** [soneek/GCMusyXTools#1]
I attempted to build a soundfont from SFA musyx crap and stumbled over this tool. Has there been any progress over the last year?

**Comment by soneek** [comment]
There has not been. I'm working on implementing soundfont building into my 3DS tool, so I'll come back to this once I feel comfortable.

**Comment by derselbst** [comment]
Ok, I [worked on it](https://github.com/derselbst/GCMusyXTools/tree/new) in the last days, will do a pull req. at some time...
